services:
  - type: web
    name: housing-rental-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn run:run"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://admin:LXK1DkE7ZANUmMsVivxvrDp1XDTqKiyy@dpg-d15n8sm3jp1c73ataeng-a/enformation_db
